default_language_version:
    python: python3

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "120", "--ignore", "E203,W503"]
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        args:
          -  --line-length=120
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]